#!/bin/bash
# create dir

while [ -n "$1" ]
do
case "$1" in
-n) name=$2 ;;
--) shift
break ;;
*) echo "$1 is not an option";;
esac
shift
done

mkdir $name

#copy input from template
cp ./templates/input.txt ./$name/input.txt

#create all template
for item in $@
do
  cp ./templates/templateCode.js "./$name/$item.js"
  cp ./templates/templateCode.cpp "./$name/$item.cpp"
done

cd $name